### ISSUE TITLE
accessing match ratio/score

### ISSUE THREAD

**Issue by Matt52** [gandersen101/spaczz#21]
Is it possible to get ratio (some sort of distance/similarity score) for each match?

**Comment by gandersen101** [comment]
Hi @Matt52 thanks for the request. Adding the fuzzy ratios for matches should be doable. I didn't include them in the Matcher/Ruler returns in order to match spaCy conventions. However, I think I can add the fuzzy ratios as custom Span attributes.

I haven't had a lot of time to work on spaczz lately, but am hoping to set some time aside in the near future. Hopefully I can add this feature in the next week or so.

Let me know if you have any other questions/issues.

**Comment by Matt52** [comment]
Hi @gandersen101 , thanks for a quick reply. That would be great if you could add it. I think it could be very useful.
BTW really awesome library. I am playing with it for few days and I really like its performance and simplicity. Nice job!

**Comment by gandersen101** [comment]
Hey @Matt52, thanks for the kind words. I'm hoping to have this feature added and to create a new release in the next day or two. I have it working locally and just need to do some additional testing and update the documentation before wrapping it up.

**Comment by gandersen101** [comment]
Hi again, @Matt52, this feature will be added in spaczz v0.3.0 set to release in the next hour or so. Please look through the updated readme (with new release notes) to see it's usage patterns. Hope it helps! Let me know if you run into any issues.

**Comment by Matt52** [comment]
Hi @gandersen101, great news! Thank you. I will let you know in case I will see any issues.
